[project]
name = "mcp-quickstart"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "groq>=0.26.0",
    "mcp[cli]>=1.9.2",
    "openai>=1.84.0",
]
